<Project>
	<PropertyGroup>
		<GameDir>C:\Program Files (x86)\Steam\steamapps\common\TerritoryControl2\</GameDir>
		<ModIdentifier>TC2.Korecontrol</ModIdentifier>
	</PropertyGroup>
	<ItemGroup>
		<Compile Include="$(GameDir)Mods\TC2.Core\Content\**\*.cs" LinkBase="TC2.Core\" />
		<None Include="$(GameDir)Mods\TC2.Core\Content\**\*" Exclude="$(GameDir)Mods\TC2.Core\Content\**\*.cs" LinkBase="TC2.Core\" />
	</ItemGroup>
	<ItemGroup>
		<Compile Include="$(GameDir)Mods\TC2.Base\Content\**\*.cs" LinkBase="TC2.Base\" />
		<None Include="$(GameDir)Mods\TC2.Base\Content\**\*" Exclude="$(GameDir)Mods\TC2.Base\Content\**\*.cs" LinkBase="TC2.Base\" />
	</ItemGroup>
	<ItemGroup>
		<Compile Include="$(GameDir)Mods\TC2.Korecontrol\content\**\*.cs" LinkBase="TC2.Korecontrol\" />
		<None Include="$(GameDir)Mods\TC2.Korecontrol\Content\**\*" Exclude="$(GameDir)Mods\TC2.Korecontrol\Content\**\*.cs" LinkBase="TC2.Korecontrol\" />
	</ItemGroup>
</Project>